[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]

[profile.default.model]
solc = "0.8.26"

[profile.default.model.solc_version]
"contracts/uniswap/*.sol" = "0.8.26"
"lib/v4-core/src/*.sol" = "0.8.26"
"lib/v4-periphery/src/*.sol" = "0.8.26"
"contracts/token/*.sol" = "0.8.28"
