/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenFactorySol from "./token_factory.sol";
export type { tokenFactorySol };
export type { Lock } from "./Lock";
